### ISSUE TITLE
使用genshin-wish-export 导出的UIGF Json进行转换

### ISSUE THREAD

**Issue by lezizijiang2** [Masterain98/genshin-wish-export-uigf-converter#1]
GWE事实上保存了已知的id字段。

其导出的JSON格式UIGF文件不符合标准的地方仅在于 原本就不存在id字段的祈愿（1.3版本前）的处理方式是[直接导出空字符串](https://github.com/biuuu/genshin-wish-export/issues/115)，1.3版本之后的祈愿id值是正确的。
因此对于JSON格式只需要补齐这部分缺失的id。
用代码简单测试了一下
``` python
 with open(file=path, mode="r+", encoding="utf-8") as fp:
        obj = json.load(fp)
        min_id = min([eval(record["id"]) for record in obj["list"] if record["id"] != ""])
        obj["list"] = list(obj["list"])
        obj["list"].reverse()
        for record in obj["list"]:
            if record["id"] == "":
                record["id"] = str(min_id-1)
                min_id -= 1
                print(record)
        fp.seek(0)
        json.dump(obj, fp)
```
修复后使用[snap.genshin](https://github.com/DGP-Studio/Snap.Genshin)导入成功，不会与后续刷新冲突。
<img width="618" alt="image" src="https://user-images.githubusercontent.com/93508480/152657247-e3cbf75c-58b7-423b-ae32-46a1b2107a8d.png">
如果需要UIGF格式的excl文件，也应当从JSON中获取正确的id来避免后续更新冲突或者舍弃近六个月记录。

**Comment by Masterain98** [comment]
biuuu/genshin-wish-export#115

genshin-wish-export已支持正确导出
